# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyPublish < Formula
  desc ""
  homepage "https://github.com/yigitozgumus/lazy-publish"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/yigitozgumus/lazy-publish/releases/download/v1.0.2/lazy-publish_1.0.2_macOS_arm64.tar.gz"
      sha256 "7eb21986add8b04d7cb777d2b5a7bf2f9f9db300da69c1e7ddbc1b7ee652fc65"

      def install
        bin.install "lazy-publish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/yigitozgumus/lazy-publish/releases/download/v1.0.2/lazy-publish_1.0.2_macOS_x86_64.tar.gz"
      sha256 "2d55d985e1a9573a30fbb62fdd59e465f1e7a6b8f980cfbb03b6f80be7f30a04"

      def install
        bin.install "lazy-publish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/yigitozgumus/lazy-publish/releases/download/v1.0.2/lazy-publish_1.0.2_Linux_x86_64.tar.gz"
      sha256 "11e4814bd689307b8e371a878ebd139c027dd2e059208bf01c89e5bf8f31c557"

      def install
        bin.install "lazy-publish"
      end
    end
  end

  depends_on "git"
  depends_on "go"
end
